# This file has been generated by node2nix 1.6.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {
    "node-zstandard-1.2.4" = {
      name = "node-zstandard";
      packageName = "node-zstandard";
      version = "1.2.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-zstandard/-/node-zstandard-1.2.4.tgz";
        sha1 = "44f62eb7cb626b948ec79dd2327d3e594ada2f06";
      };
    };
  };
in
{
  "fluorine-git+https://github.com/fohristiwhirl/fluorine" = nodeEnv.buildNodePackage {
    name = "Fluorine";
    packageName = "Fluorine";
    version = "1.2.4";
    src = fetchgit {
      url = "https://github.com/fohristiwhirl/fluorine";
      rev = "185340522322222afba6058e19a4041caf2a435b";
      sha256 = "8adcdd2913862535dbf7bb061f9e1a9d79404c8085a43cb978aa9c78e136eaff";
    };
    dependencies = [
      sources."node-zstandard-1.2.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "Replay viewer for Halite 3";
    };
    production = true;
    bypassCache = true;
  };
  "iodine-git+https://github.com/fohristiwhirl/iodine" = nodeEnv.buildNodePackage {
    name = "Iodine";
    packageName = "Iodine";
    version = "0.2.0";
    src = fetchgit {
      url = "https://github.com/fohristiwhirl/iodine";
      rev = "bf77fa84a18d97bdfacefa954f6d3fa0a3e1d0b3";
      sha256 = "7573790efa119fb4aa4b9d93d9b4515b202e0bc4b6932f35589a63802063d014";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Realtime viewer for Halite 3";
    };
    production = true;
    bypassCache = true;
  };
}